version: '3.8'

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test-app
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-app.rule=Host(`chromecast-receiver-eoa98f-582647-91-98-85-187.traefik.me`)"
      - "traefik.http.routers.test-app.tls=true"
      - "traefik.http.routers.test-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.test-app.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.test-cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.test-cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.routers.test-app.middlewares=test-cors"
    networks:
      - test-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  test-network:
    driver: bridge
